services:
  app:
    build: app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - CGO_ENABLED=0
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
      - GIN_MODE=debug
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

